version: "3.7"
services:
  api:
    image: "satellite-tracker:latest"
    depends_on:
      - db
    ports:
      - 8000:80
    env_file:
      - ../env_files/.dev.env
    volumes:
      - ../src/:/app/app/
    command: bash -c "while true; do sleep 1; done"

  db:
    image: "postgres:13"
    env_file:
      - ../env_files/.dev.env
    volumes:
      - app-db-data-dev:/var/lib/postgresql/data/pgdata

  testdb:
    image: "postgres:13"
    env_file:
      - ../env_files/.test.env

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    env_file:
      - ../env_files/.dev.env

volumes:
  app-db-data-dev:

networks:
  default:
    external:
      name: $NETWORK_NAME
