version: "3.7"
services:
  api:
    image: "satellite-tracker:latest"
    init: true
    depends_on:
      - db
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: /start-reload.sh

  db:
    image: "postgres:13"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db

networks:
  default:
    external:
      name: $NETWORK_NAME